# Generated by Django 4.2.5 on 2023-10-20 06:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "Exchanges",
            },
        ),
        migrations.CreateModel(
            name="CryptoCurrencyPair",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=128)),
                (
                    "exchange",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.exchange"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Crypto Currencies",
            },
        ),
    ]
