# Generated by Django 4.2.5 on 2023-10-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchange",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
