# Generated by Django 4.2.5 on 2023-10-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_exchange_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrencypair",
            name="symbol",
            field=models.CharField(max_length=256),
        ),
    ]
